// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/ugdmint/v1beta1/mint_record.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MintRecord represents a record of minting activity
type MintRecord struct {
	BlockHeight int64                                    `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Account     string                                   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Amount      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MintRecord) Reset()         { *m = MintRecord{} }
func (m *MintRecord) String() string { return proto.CompactTextString(m) }
func (*MintRecord) ProtoMessage()    {}
func (*MintRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b2ccc048ad7222, []int{0}
}
func (m *MintRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintRecord.Merge(m, src)
}
func (m *MintRecord) XXX_Size() int {
	return m.Size()
}
func (m *MintRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_MintRecord.DiscardUnknown(m)
}

var xxx_messageInfo_MintRecord proto.InternalMessageInfo

func (m *MintRecord) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MintRecord) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MintRecord) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func init() {
	proto.RegisterType((*MintRecord)(nil), "cosmos.ugdmint.v1beta1.MintRecord")
}

func init() {
	proto.RegisterFile("cosmos/ugdmint/v1beta1/mint_record.proto", fileDescriptor_39b2ccc048ad7222)
}

var fileDescriptor_39b2ccc048ad7222 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0x2a, 0x15, 0x91, 0x76, 0x21, 0x42, 0xa8, 0x74, 0x70, 0x0b, 0x53, 0x54, 0xa9,
	0xb1, 0x0a, 0x13, 0x6b, 0x91, 0x10, 0x0b, 0x4b, 0xd8, 0x58, 0xaa, 0xc4, 0xb1, 0x5c, 0xd3, 0xc6,
	0x57, 0xc5, 0x0e, 0xa2, 0x6f, 0xc1, 0xcc, 0x13, 0x20, 0xa6, 0x3e, 0x04, 0x43, 0xc7, 0x8e, 0x4c,
	0x80, 0x9a, 0xa1, 0xaf, 0x81, 0xe2, 0x38, 0x15, 0x8b, 0x7d, 0xf7, 0xdf, 0x6f, 0x7d, 0xbf, 0x7c,
	0xae, 0x4f, 0x41, 0xa5, 0xa0, 0x48, 0xce, 0x93, 0x54, 0x48, 0x4d, 0x9e, 0x47, 0x31, 0xd3, 0xd1,
	0x88, 0x94, 0xcd, 0x24, 0x63, 0x14, 0xb2, 0x24, 0x58, 0x64, 0xa0, 0xc1, 0x3b, 0xad, 0x9c, 0x81,
	0x75, 0x06, 0xd6, 0xd9, 0x3d, 0x8e, 0x52, 0x21, 0x81, 0x98, 0xb3, 0xb2, 0x76, 0x4f, 0x38, 0x70,
	0x30, 0x25, 0x29, 0x2b, 0xab, 0x62, 0x8b, 0x8a, 0x23, 0xc5, 0xf6, 0x1c, 0x0a, 0x42, 0x56, 0xf3,
	0x8b, 0x4f, 0xe4, 0xba, 0xf7, 0x42, 0xea, 0xd0, 0x50, 0xbd, 0x73, 0xb7, 0x1d, 0xcf, 0x81, 0xce,
	0x26, 0x53, 0x26, 0xf8, 0x54, 0x77, 0x50, 0x1f, 0xf9, 0x8d, 0xb0, 0x65, 0xb4, 0x3b, 0x23, 0x79,
	0x1d, 0xf7, 0x30, 0xa2, 0x14, 0x72, 0xa9, 0x3b, 0x07, 0x7d, 0xe4, 0x1f, 0x85, 0x75, 0xeb, 0x2d,
	0xdd, 0x66, 0x94, 0x9a, 0x41, 0xa3, 0xdf, 0xf0, 0x5b, 0x97, 0x67, 0x81, 0x4d, 0x5f, 0xc2, 0xeb,
	0xe8, 0xc1, 0x0d, 0x08, 0x39, 0xbe, 0x5d, 0x7f, 0xf7, 0x9c, 0x8f, 0x9f, 0x9e, 0xcf, 0x85, 0x9e,
	0xe6, 0x71, 0x40, 0x21, 0x25, 0x36, 0x69, 0x75, 0x0d, 0x55, 0x32, 0x23, 0x7a, 0xb9, 0x60, 0xca,
	0x3c, 0x50, 0x6f, 0xbb, 0xd5, 0xa0, 0x3d, 0x67, 0x3c, 0xa2, 0xcb, 0x49, 0x19, 0x5f, 0xbd, 0xef,
	0x56, 0x03, 0x14, 0x5a, 0xe0, 0xf8, 0x61, 0xbd, 0xc5, 0x68, 0xb3, 0xc5, 0xe8, 0x77, 0x8b, 0xd1,
	0x6b, 0x81, 0x9d, 0x4d, 0x81, 0x9d, 0xaf, 0x02, 0x3b, 0x8f, 0xd7, 0xff, 0x08, 0xb9, 0x14, 0x3c,
	0x13, 0xc9, 0x70, 0x91, 0xc1, 0x13, 0xa3, 0xba, 0x46, 0xd5, 0x6b, 0x78, 0xd9, 0x2f, 0xc4, 0x80,
	0xe3, 0xa6, 0xf9, 0xa2, 0xab, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x94, 0x4f, 0xac, 0xaf,
	0x01, 0x00, 0x00,
}

func (m *MintRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMintRecord(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintMintRecord(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0x12
	}
	if m.BlockHeight != 0 {
		i = encodeVarintMintRecord(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMintRecord(dAtA []byte, offset int, v uint64) int {
	offset -= sovMintRecord(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MintRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovMintRecord(uint64(m.BlockHeight))
	}
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovMintRecord(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovMintRecord(uint64(l))
		}
	}
	return n
}

func sovMintRecord(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMintRecord(x uint64) (n int) {
	return sovMintRecord(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MintRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMintRecord
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMintRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMintRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMintRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMintRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMintRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMintRecord
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMintRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMintRecord(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMintRecord
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMintRecord(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMintRecord
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMintRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMintRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMintRecord
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMintRecord
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMintRecord
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMintRecord        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMintRecord          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMintRecord = fmt.Errorf("proto: unexpected end of group")
)
